title: Shril
description: >-
  He's writing in Bahasa about web technology and experience as a journal  for
  documentation things that he learned, meet him <a
  href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: 'https://github.com/shril/shril.github.io'
mode: dark
author:
  name: Shril Kumar
  bio: >-
    Welcome to my Cosmos, earthling! I am Data Engineer by profession. I design and develop solutions which process TBs of data everyday.
    I like Physics and Mathematics. So being a full time nerd, I am trying to put a dent in the universe in my own way.
  username: shril
  email: shrilkr@outlook.com
  avatar: /assets/img/avatar.jpg
url: 'https://shril.github.io/'
baseurl: null
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
